openapi: 3.1.0
info:
  title: OpenAPI Plant Store
  description: A sample API that uses a plant store as an example to demonstrate features in the OpenAPI specification
  license:
    name: MIT
  version: 1.0.0
servers:
  - url: https://{Subdomain}.api.clarussoftware.co.uk
    description: Staging
    variables:
      Subdomain:
        default: demo
        description: Customer subdomain assigned by Clarus WMS
security:
  - ApiKeyAuth: []
paths:
  /graphql:
    post:
      summary: Retrieve a Warehouse
      deprecated: false
      description: etrieve a Warehous
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  format: textarea
                variables:
                  type: object
                  properties: {}
                  nullable: true
              required:
                - query
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/All%20Warehouses'
              examples:
                '1':
                  summary: Success
                  value:
                    data:
                      warehouses:
                        all:
                          pageInfo:
                            hasNextPage: false
                            hasPreviousPage: false
                            startCursor: MQ
                            endCursor: MQ
                          edges:
                            - cursor: MQ
                              node:
                                id: '1'
                                code: WAR01
                                name: Warehouse 01
                                address:
                                  id: '5'
                                  code: null
                                  name: null
                                  address_1: null
                                  address_2: null
                                  address_3: null
                                  address_4: null
                                  address_5: null
                                  postcode: '52123'
                                  country_code: GB-UKM
                                  email_address: null
                                  phone_number: null
                                  is_active: true
                                  external_delivery_id: null
                                  external_system_reference1: null
                                  external_system_reference2: null
                                  external_system_reference3: null
                                  created_at: '2019-05-29T09:34:05.693+01:00'
                                  created_at_formatted: 29/05/2019 09:34
                                  updated_at: '2024-06-20T13:59:46.882+01:00'
                                  updated_at_formatted: 20/06/2024 13:59
                                site:
                                  id: '1'
                                  code: DEF001
                                  name: Default Site
                                opening_times_enabled: true
                                opening_times:
                                  id: '1'
                                  monday_open: true
                                  monday_from: '09:00'
                                  monday_to: '17:00'
                                  tuesday_open: true
                                  tuesday_from: '09:00'
                                  tuesday_to: '17:00'
                                  wednesday_open: true
                                  wednesday_from: '09:00'
                                  wednesday_to: '17:00'
                                  thursday_open: true
                                  thursday_from: '09:00'
                                  thursday_to: '17:00'
                                  friday_open: true
                                  friday_from: '09:00'
                                  friday_to: '12:00'
                                  saturday_open: false
                                  saturday_from: '00:00'
                                  saturday_to: '23:59'
                                  sunday_open: false
                                  sunday_from: '00:00'
                                  sunday_to: '23:59'
                                  created_at: '2023-12-07T15:55:25.373+00:00'
                                  created_at_formatted: 07/12/2023 15:55
                                  updated_at: '2023-12-07T15:55:25.373+00:00'
                                  updated_at_formatted: 07/12/2023 15:55
                                consolidate_pick_enabled: true
                                default_goods_in_bay:
                                  id: '1'
                                default_goods_in_bay_id: '1'
                                default_goods_out_bay:
                                  id: '2'
                                default_goods_out_bay_id: '2'
                                external_system_reference1: '594866000000063175'
                                external_system_reference2: null
                                external_system_reference3: null
                                trusted_warehouses: []
                                created_at: '2017-04-13T21:05:37.508+01:00'
                                updated_at: '2024-06-20T11:22:27.491+01:00'
                '2':
                  summary: Exception
                  value:
                    data:
                      sites:
                        all:
                          edges: []
          headers: {}
  /api/sites:
    post:
      summary: Create a Site
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                data:
                  type: object
                  properties:
                    attributes:
                      $ref: '#/components/schemas/Site'
                  required:
                    - attributes
              required:
                - data
              $ref: '#/components/schemas/Site1'
            example:
              data:
                attributes:
                  code: SITE55
                  name: Site 55
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The unique identifier of the resource.
                    readOnly: true
                  code:
                    type: string
                    description: The unique code for the site. This can be any series of characters that are unique to your operation.
                    title: ''
                    maxLength: 50
                  name:
                    type: string
                    description: The identifiable name of the site.
                    maxLength: 50
                  tier:
                    type: string
                    description: |-
                      The tier of the site related to the Control of major accident hazards (COMAH) Establishment Tier.

                      If you store or use more than the lower threshold for a dangerous substance your site is classed as a "lower" tier establishment. If you store or use more than the higher threshold your site is an "upper" tier establishment.

                      If this does not apply to your site, then select "none".
                    enum:
                      - none
                      - lower
                      - upper
                    default: none
                  boolean1:
                    type: boolean
                    description: A bespoke field that can be used to store any custom true or false value against the resource.
                    nullable: true
                  boolean2:
                    type: boolean
                    description: A bespoke field that can be used to store any custom true or false value against the resource.
                    nullable: true
                  boolean3:
                    type: boolean
                    description: A bespoke field that can be used to store any custom true or false value against the resource.
                    nullable: true
                  boolean4:
                    type: boolean
                    description: A bespoke field that can be used to store any custom true or false value against the resource.
                    nullable: true
                  boolean5:
                    type: boolean
                    description: A bespoke field that can be used to store any custom true or false value against the resource.
                    nullable: true
                  datetime1:
                    type: string
                    format: date-time
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    maxLength: 29
                    minLength: 29
                    description: A bespoke field that can be used to store any custom date time value against the resource.
                    nullable: true
                  datetime2:
                    type: string
                    format: date-time
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    maxLength: 29
                    minLength: 29
                    description: A bespoke field that can be used to store any custom date time value against the resource.
                    nullable: true
                  datetime3:
                    type: string
                    format: date-time
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    maxLength: 29
                    minLength: 29
                    description: A bespoke field that can be used to store any custom date time value against the resource.
                    nullable: true
                  datetime4:
                    type: string
                    format: date-time
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    maxLength: 29
                    minLength: 29
                    description: A bespoke field that can be used to store any custom date time value against the resource.
                    nullable: true
                  datetime5:
                    type: string
                    format: date-time
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    maxLength: 29
                    minLength: 29
                    description: A bespoke field that can be used to store any custom date time value against the resource.
                    nullable: true
                  default:
                    type: boolean
                    default: false
                    description: |-
                      A true or false value that indicates whether this site will be the default site for new Warehouses. 

                      Only one Site can be set as the default at any one point.
                      If true is set for the creation or update of a Site, then this will become the default if it so not already.
                  external_system_reference1:
                    type: string
                    description: A field commonly use to associate the resource with the reference of a matching entity in an external system.
                    nullable: true
                  external_system_reference2:
                    type: string
                    description: A field commonly use to associate the resource with the reference of a matching entity in an external system.
                    nullable: true
                  external_system_reference3:
                    type: string
                    description: A field commonly use to associate the resource with the reference of a matching entity in an external system.
                    nullable: true
                  integer1:
                    type: integer
                    description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
                    nullable: true
                  integer2:
                    type: integer
                    description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
                    nullable: true
                  integer3:
                    type: integer
                    description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
                    nullable: true
                  integer4:
                    type: integer
                    description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
                    nullable: true
                  integer5:
                    type: integer
                    description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
                    nullable: true
                  string1:
                    type: string
                    description: A bespoke field that can be used to store any text against the resource.
                    nullable: true
                  string2:
                    type: string
                    description: A bespoke field that can be used to store any text against the resource.
                    nullable: true
                  string3:
                    type: string
                    description: A bespoke field that can be used to store any text against the resource.
                    nullable: true
                  string4:
                    type: string
                    description: A bespoke field that can be used to store any text against the resource.
                    nullable: true
                  string5:
                    type: string
                    description: A bespoke field that can be used to store any text against the resource.
                    nullable: true
                  created_at:
                    type: string
                    description: The date and time the resource was created in ISO-8601 format.
                    format: date-time
                    maxLength: 29
                    minLength: 29
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    readOnly: true
                  updated_at:
                    type: string
                    description: The date and time the resource was last updated in ISO-8601 format.
                    format: date-time
                    examples:
                      - '2023-11-09T10:06:36.593+00:00'
                    pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
                    maxLength: 29
                    minLength: 29
                    readOnly: true
                required:
                  - id
                  - code
                  - name
                  - tier
          headers: {}
  /plants:
    get:
      description: Returns all plants from the system that the user has access to
      parameters:
        - name: limit
          in: query
          description: The maximum number of results to return
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Plant response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
        '400':
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      description: Creates a new plant in the store
      requestBody:
        description: Plant to add to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPlant'
        required: true
      responses:
        '200':
          description: plant response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Plant'
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /plants/{id}:
    delete:
      description: Deletes a single plant based on the ID supplied
      parameters:
        - name: id
          in: path
          description: ID of plant to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Plant deleted
          content: {}
        '400':
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
webhooks:
  /plant/webhook:
    post:
      description: Information about a new plant added to the store
      requestBody:
        description: Plant added to the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewPlant'
      responses:
        '200':
          description: Return a 200 status to indicate that the data was received successfully
components:
  schemas:
    Address:
      type: object
      required:
        - id
        - name
        - is_active
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          format: int64
          description: Unique internal identifier for the address record.
        name:
          type: string
          description: A human-readable name for the address. Often represents a site, person, or organisation.
        address_1:
          type: string
          maxLength: 80
          description: Primary address line, typically used for building name or street address.
        address_2:
          type: string
          maxLength: 80
          description: Secondary address line, often used for unit or suite numbers.
        address_3:
          type: string
          maxLength: 80
          description: Tertiary address line, available for additional location details.
        address_4:
          type: string
          maxLength: 80
          description: Optional fourth address line for extended address formatting needs.
        address_5:
          type: string
          maxLength: 80
          description: Optional fifth address line, used in complex or international formats.
        postcode:
          type: string
          maxLength: 10
          description: Postal code or ZIP code for the address.
        country_code:
          type: string
          maxLength: 2
          description: Two-letter ISO 3166-1 alpha-2 country code (e.g., "GB" for United Kingdom).
        email_address:
          type: string
          format: email
          description: Contact email associated with this address, if available.
        phone_number:
          type: string
          description: Phone number linked to this address, preferably in international format (e.g., +44...).
        code:
          type: string
          description: Optional internal or external reference code used to identify the address programmatically.
        addressable_type:
          type: string
          description: Polymorphic type representing the kind of entity this address is associated with (e.g., "Warehouse", "Customer").
        external_delivery_id:
          type: string
          description: Identifier used by an external delivery system to reference this address.
        external_system_reference1:
          type: string
          description: Optional external reference field #1 for integrations or third-party systems.
        external_system_reference2:
          type: string
          description: Optional external reference field #2 for integrations or third-party systems.
        external_system_reference3:
          type: string
          description: Optional external reference field #3 for integrations or third-party systems.
        is_active:
          type: boolean
          default: true
          description: Indicates whether this address is active and available for use.
        created_at:
          type: string
          format: date-time
          description: ISO 8601 timestamp marking when the address was created.
        updated_at:
          type: string
          format: date-time
          description: ISO 8601 timestamp marking the last time the address was modified.
        created_at_formatted:
          type: string
          description: Human-readable formatted version of the creation date (e.g., "12 Jan 2024").
        updated_at_formatted:
          type: string
          description: Human-readable formatted version of the update date (e.g., "20 Jun 2025").
    Site:
      type: object
      properties:
        id:
          type: integer
          description: The unique identifier of the resource.
          readOnly: true
        code:
          type: string
          description: The unique code for the site. This can be any series of characters that are unique to your operation.
          title: ''
          maxLength: 50
        name:
          type: string
          description: The identifiable name of the site.
          maxLength: 50
        tier:
          type: string
          description: |-
            The tier of the site related to the Control of major accident hazards (COMAH) Establishment Tier.

            If you store or use more than the lower threshold for a dangerous substance your site is classed as a "lower" tier establishment. If you store or use more than the higher threshold your site is an "upper" tier establishment.

            If this does not apply to your site, then select "none".
          enum:
            - none
            - lower
            - upper
          default: none
        boolean1:
          type: boolean
          description: A bespoke field that can be used to store any custom true or false value against the resource.
          nullable: true
        boolean2:
          type: boolean
          description: A bespoke field that can be used to store any custom true or false value against the resource.
          nullable: true
        boolean3:
          type: boolean
          description: A bespoke field that can be used to store any custom true or false value against the resource.
          nullable: true
        boolean4:
          type: boolean
          description: A bespoke field that can be used to store any custom true or false value against the resource.
          nullable: true
        boolean5:
          type: boolean
          description: A bespoke field that can be used to store any custom true or false value against the resource.
          nullable: true
        datetime1:
          type: string
          format: date-time
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          maxLength: 29
          minLength: 29
          description: A bespoke field that can be used to store any custom date time value against the resource.
          nullable: true
        datetime1_formatted:
          type: string
          description: The datetime1 field in readable format, localised to UTC.
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          nullable: true
        datetime2:
          type: string
          format: date-time
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          maxLength: 29
          minLength: 29
          description: A bespoke field that can be used to store any custom date time value against the resource.
          nullable: true
        datetime2_formatted:
          type: string
          description: The datetime2 field in readable format, localised to UTC.
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          nullable: true
        datetime3:
          type: string
          format: date-time
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          maxLength: 29
          minLength: 29
          description: A bespoke field that can be used to store any custom date time value against the resource.
          nullable: true
        datetime3_formatted:
          type: string
          description: The datetime3 field in readable format, localised to UTC.
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          nullable: true
        datetime4:
          type: string
          format: date-time
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          maxLength: 29
          minLength: 29
          description: A bespoke field that can be used to store any custom date time value against the resource.
          nullable: true
        datetime4_formatted:
          type: string
          description: The datetime4 field in readable format, localised to UTC.
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          nullable: true
        datetime5:
          type: string
          format: date-time
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          maxLength: 29
          minLength: 29
          description: A bespoke field that can be used to store any custom date time value against the resource.
          nullable: true
        datetime5_formatted:
          type: string
          description: The datetime5 field in readable format, localised to UTC.
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          nullable: true
        default:
          type: boolean
          default: false
          description: |-
            A true or false value that indicates whether this site will be the default site for new Warehouses. 

            Only one Site can be set as the default at any one point.
            If true is set for the creation or update of a Site, then this will become the default if it so not already.
        external_system_reference1:
          type: string
          description: A field commonly use to associate the resource with the reference of a matching entity in an external system.
          nullable: true
        external_system_reference2:
          type: string
          description: A field commonly use to associate the resource with the reference of a matching entity in an external system.
          nullable: true
        external_system_reference3:
          type: string
          description: A field commonly use to associate the resource with the reference of a matching entity in an external system.
          nullable: true
        integer1:
          type: integer
          description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
          nullable: true
        integer2:
          type: integer
          description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
          nullable: true
        integer3:
          type: integer
          description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
          nullable: true
        integer4:
          type: integer
          description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
          nullable: true
        integer5:
          type: integer
          description: A bespoke field that can be used to store any custom numerical (integer) value against the resource.
          nullable: true
        string1:
          type: string
          description: A bespoke field that can be used to store any text against the resource.
          nullable: true
        string2:
          type: string
          description: A bespoke field that can be used to store any text against the resource.
          nullable: true
        string3:
          type: string
          description: A bespoke field that can be used to store any text against the resource.
          nullable: true
        string4:
          type: string
          description: A bespoke field that can be used to store any text against the resource.
          nullable: true
        string5:
          type: string
          description: A bespoke field that can be used to store any text against the resource.
          nullable: true
        created_at:
          type: string
          description: The date and time the resource was created in ISO-8601 format.
          format: date-time
          maxLength: 29
          minLength: 29
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          readOnly: true
        updated_at:
          type: string
          description: The date and time the resource was last updated in ISO-8601 format.
          format: date-time
          examples:
            - '2023-11-09T10:06:36.593+00:00'
          pattern: ^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}[+-]\\d{2}:\\d{2}$
          maxLength: 29
          minLength: 29
          readOnly: true
        created_at_formatted:
          type: string
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          description: The date and time the resource was created in readable format, localised to UTC.
        updated_at_formatted:
          type: string
          readOnly: true
          format: date-time
          examples:
            - 09/11/2023 10:06
          pattern: ^\\d{2}/\\d{2}/\\d{4} \\d{2}:\\d{2}$
          maxLength: 16
          minLength: 16
          description: The date and time the resource was last updated in readable format, localised to UTC.
      required:
        - id
        - name
        - tier
        - code
    Site1:
      type: object
      properties:
        data:
          type: object
          properties:
            attributes:
              $ref: '#/components/schemas/Site'
              description: The attributes of the Site resource.
          required:
            - attributes
          description: The data object wrapper.
      required:
        - data
      description: The body of the request.
    Plant:
      required:
        - name
      type: object
      properties:
        name:
          description: The name of the plant
          type: string
        tag:
          description: Tag to specify the type
          type: string
    NewPlant:
      allOf:
        - $ref: '#/components/schemas/Plant'
        - required:
            - id
          type: object
          properties:
            id:
              description: Identification number of the plant
              type: integer
              format: int64
    Error:
      required:
        - error
        - message
      type: object
      properties:
        error:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: Authorization
      description: |
        The format of the value should be:
        `Token token="$myToken", email="$myEmail"`

        Where:
        * `$myToken` is provided in the response to a successful login
        * `$myEmail` is the email of the user who has authenticated
        You can only have one concurrent login per account, so if you login to the application via the web browser you will be required to reauthenticate.

